spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    data: 
      - classpath:2.AWSCertifiedDeveloper–Associate.sql # 시작할때 실행시킬 script
      # - classpath:2.SQLP.sql 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true