spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    data:  # 시작할때 실행시킬 script
      - classpath:1.AWSCertifiedDeveloper–Associate.sql
      - classpath:2.SQLP.sql 
      - classpath:3.CBPCertification.sql
      - classpath:4.ComputerScience.sql
      - classpath:5.SQLD.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true