spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://localhost/quizeey
#    url: jdbc:mariadb://52.35.43.187/quizeey
    username: samurae83
    password: 1l0v2ujin
    driver-class-name: org.mariadb.jdbc.Driver